# Generated by Django 4.2.6 on 2024-02-19 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_client_mobile_operator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Send_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='mobile_operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.operators'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tags'),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.send_status'),
        ),
        migrations.AlterField(
            model_name='sender',
            name='mobile_operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.operators'),
        ),
        migrations.AlterField(
            model_name='sender',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tags'),
        ),
    ]
